name: idb_sqflite
description: IndexedDB API on top of sqflite for Flutter (Desktop and Mobile) and DartVM io applications
homepage: https://github.com/tekartik/idb_sqflite/tree/master/idb_sqflite
version: 1.3.6+1
topics:
  - database

environment:
  sdk: ^3.10.0

dependencies:
  idb_shim: '>=2.8.0-2 <4.0.0'
  sqflite_common: '>=2.5.4+3 <4.0.0'
  meta: '>=1.3.0 <3.0.0'
  synchronized: '>=3.1.0+1 <5.0.0'
dev_dependencies:
  sqflite_common_ffi: '>=2.3.0'
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  lints: '>=1.0.1'
