name: idb_sqflite_example
description: idb_sqflite example
version: 0.1.0

environment:
  sdk: ">=2.4.0-dev.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  idb_sqflite:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
